image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build

lint:
  stage: test
  script:
    - docker run --rm myapp-test flake8 --exclude=*migrations*,*venv*,*__pycache__* .
  before_script:
    - docker build -f Dockerfile --target test -t myapp-test .
  only:
    - merge_requests
    - tags

safety:
  stage: test
  script:
    - docker run --rm myapp-test pip-audit -r /opt/requirements.txt
  before_script:
    - docker build -f Dockerfile --target test -t myapp-test .
  only:
    - merge_requests
    - tags

unit-test:
  stage: test
  script:
    - docker run --env-file .env --rm myapp-test pytest /opt/tests
  before_script:
    - docker build -f Dockerfile --target test -t myapp-test .
  only:
    - merge_requests
    - tags

build:
  stage: build
  needs: ["lint", "safety", "unit-test"]
  script:
    - docker login -p $registry_password -u $registry_user registry.jacobscodingstuff.com
    - docker build -t registry.jacobscodingstuff.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .
    - docker push registry.jacobscodingstuff.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
  only:
    - tags
  except:
    - branches